Repository RT-Thread/packages, pull requests merged in 2021-09, with the labels that each got.

#1034 [bsal]add nordic uart service sample
  iot/bsal/Kconfig
Labels: +2

#1027 [peripherals][i2c-tools] select libc
  peripherals/i2c-tools/Kconfig
Labels: +1

#1029 新增御坂网络AT24CXX驱动
  peripherals/Kconfig
  peripherals/Misaka_AT24CXX/Kconfig
  peripherals/Misaka_AT24CXX/package.json
Labels: +1

#1033 Add HM package
  iot/Kconfig
  iot/btstack/Kconfig
  iot/hm/Kconfig
  iot/hm/package.json
Labels: +2

#1044 [add] bouffalolab mcu sdk
  peripherals/Kconfig
  peripherals/bouffalolab_sdk/Kconfig
  peripherals/bouffalolab_sdk/package.json
Labels: +1

#1040 add: PLL
  misc/phase-locked-loop/Kconfig
  misc/phase-locked-loop/package.json
Labels: +1

#1048 u8g2-offical
  multimedia/Kconfig
  multimedia/u8g2/Kconfig
  multimedia/u8g2/u8g2-official/Kconfig
  multimedia/u8g2/u8g2-official/package.json
  multimedia/u8g2/u8g2/Kconfig
  multimedia/u8g2/u8g2/package.json
  peripherals/Kconfig
Labels: +1, +2
