Repository RT-Thread/packages, pull requests merged in 2022-04, with the labels that each got.

#1231 [ADD]add tiny flash database Library.
  system/Kconfig
  system/TFDB/Kconfig
  system/TFDB/package.json
Labels: +1

#1234 [update] add dependent item for rw007.
  iot/WiFi/rw007/Kconfig
Labels: +2

#1235 [tinyusb] add hid example
  system/TinyUSB/Kconfig
Labels: +1

#1233 [ADD]add hash-match package.
  tools/Kconfig
  tools/hash-match/Kconfig
  tools/hash-match/package.json
Labels: +1

#1237 qboot release v1.06
  system/qboot/Kconfig
  system/qboot/package.json
Labels: +1, +2

#1240 update wk2124 to v2.0.0
  peripherals/wk2124/Kconfig
  peripherals/wk2124/package.json
Labels: +1
